sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: FQrZs2IOv2TK1iHKA+8TNeD5R88WK6uWJ2rX34FEZ+wdwGNGTq7hUQevd/xHH9jpXv635komkzePjMqqwPbkARmb+7sZPkkBL5gTJpVqCtnkuTWalz4xBM2kuoTbzvKZxKG4+6DdxS9SoJiFhB76/W02XrnnZF7s0zR0dhn2JELEA/AkKWGTlo358dNgYf360Dt7A3DoWxLCAX6E7zCRtThftGWNejigbejCiBgLeS5nxlL44RKZpkgrIiw9tXY6dchieUV6cOxwRKze0fmuveRwMFJpU30ssaOklZ4LofVrRl+haS3d7cap/4AFIrwNew4NcbbLfI/4N47PK0bVZ/FeuWG4PRlA23lLPbhrLgXCiEIfXgBvfsL3HzOe3m8Bt4p8E0lWxbwrbdtY7L8NULYh3eg3PxP5+V4kEWi81EcSboQWAHU3Oz/daZfceOfd/wWy/QYF0irTwZ3eak07/W2Yz7gqkfqoXUTPfSBZCkIcVyOfxSsrDFfPcBUL3skskReC9XQ6pufPqdulw0KS1mSNZKoqQoyFHgsA6rJaqYs20Ffva/r1qh3XHi1qExkorPTQ5nq2gEB/ngoX08Xrv6IK9Emg9Y29nELQi1sFAGBzgx7ipH8/N/g41r6kZrssSBnbWLu8dscVjDf4/zDWfTGltjU3lvlP5WUw07IWm7U=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: WcBpa9pHSG1S8hojg88eT64WAdQUGEOrLhAnjjyV9o5wAfswgrQbZz73uispu0M2JnEuLQWjywdMHWAcKFOUks1QTnEW3YyBElhR9S801XaFK+3DtBcZQHZcQtSxE4jwajfrXeGKDkqX1zavOZWfsTVYFG8YzLVDFfDwr6C0Tpf2TuWWGE/XS9PsGsf7PJZYgT3oqaU61vnOQE4i8tPeyjy3Q4qD80zT6vnkSyvEAt6zyKjfuE27tJwrbx9CBvY0pyjwClZRxyMEnd7YniN+0N2WP++407ZO94bUwbDuKrjs2qXQHvnqt/EOtwvD8hm3LubyZbHD1BYqTAbSqXa4IHbilNNhBAbGnt4SLSiKq2FoXF/AUOfMyfQinWtbb7sW3prLpvbgOtbnWkkNRNHbKAqex2zBAlyLZsEsSKzUIra662ZsdX7eL1u62DejQH+YT+V3PUQvo25QReS1MBg/yiN1xWfd22k9jucNwI+h4Jh1m1MizIYyrOtZTOZpefEc9+ZSs/9XR2exgbBFqx3oQsdyLR7WqhUpr2GwTKDoR2uo1e1sbXIrOnIVF+sBEdo2m3Js0iyuuyJ2/7z3aOGXmHafEnaZj/82iyYaYs5TXMYD4TOYOYE7pRb2YKAltDhpRdQuW+Kbjj1lT4ziO0AkoOnAr+tRDwzYkPyPUDTpMhE=
